### ISSUE TITLE
not working on the newest vscode v1.52.0

### ISSUE THREAD

**Issue by sohibegit** [mjbvz/vscode-folder-source-actions#3]

**Comment by lukepighetti** [comment]
Friendly ping.

**Comment by mjbvz** [comment]
@lukepighetti PRs welcome

**Comment by sohibegit** [comment]
https://github.com/mjbvz/vscode-folder-source-actions/blob/aea1d1b3bb306a251fe66ed6d55069f83f36cc1b/src/extension.ts#L67

kind.value));  should fix the issue i guess

**Comment by lukepighetti** [comment]
The only reason I friendly pinged you was because this breaks your plugin. If this were a nit I wouldn't have bothered.

**Comment by mjbvz** [comment]
@lukepighetti Please don't post comments on issues unless you have something to contribute. I maintain like a hundred open source projects (sometimes for products I don't even use) and pinging for attention gets old quickly

If this issue matters to you, then help fix it

**Comment by lukepighetti** [comment]
Please forgive me for trying to inform you that one of the packages you maintain is unusable. From: a fellow open source contributor who appreciates it when someone informs me that something is more broken than I understand it to be.

**Comment by lukepighetti** [comment]
Here's your PR. Don't be a dick when a fellow open source maintainer is trying to politely ping you about a showstopping regression in one of your published packages. https://github.com/mjbvz/vscode-folder-source-actions/pull/5

**Comment by lukepighetti** [comment]
Here's your PR. https://github.com/mjbvz/vscode-folder-source-actions/pull/5 

Big thanks to @sohibegit for saving me a bunch of time by providing a solution that I confirmed works and solves the regression.

I wouldn't have been annoyed by your response if you had put 15 seconds of thought into suggesting a path forward to success here. From: a fellow open source maintainer.

Should also close issue https://github.com/mjbvz/vscode-folder-source-actions/issues/4

**Comment by mjbvz** [comment]
@lukepighetti Thanks for the PR but no need for the personal comments

**Comment by mjbvz** [comment]
Unfortunately that did not actually seem fix the bug. Looking into it

**Comment by mjbvz** [comment]
Ok, to get the fix you'll need both the new extension version **and the next version of VS Code (1.54+)**

A VS Code update likely broken this a few versions back. This extension was passing the expected type for `vscode.executeCodeActionProvider ` but VS Code started mishandling it by expecting a string.  After review, I decided it makes more sense to have `vscode.executeCodeActionProvider` just take a string in the first place. This is more consistent with our other commands
