### ISSUE TITLE
Organize folder is not working on version 0.2.0 on vscode 1.53.2

### ISSUE THREAD

**Issue by Hossein13M** [mjbvz/vscode-folder-source-actions#4]
As the tutorial explains, I attempted to use `Organize Imports in Folder`, but no luck working. however, when I use the command `Organize Imports` on a single file by myself it works as expected.
Do I need to add anything to my `.editorconfig` file?
VSCode version: 1.53.2

**Comment by mjbvz** [comment]
What language is this for?

**Comment by Devorein** [comment]
I'm facing the same issue in vscode 1.53.2 as well. In my case, all of the files end with the .ts extension.

**Comment by mjbvz** [comment]
Sounds like a duplicate of #3. See that issue for more details
